import "../styles/variables.module.scss";
import Head from "next/head";
export default function MyApp({ Component, pageProps }) {
  //component dai dien cho 1 page match url
  // khi thay doi gi ben trong app phai start lai server
  return (
    <>
      <Head>
        <title>Study Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />;
    </>
  );
}
